
/**
 * @file packages/@datasphere/core/business/retention-analysis/types.ts
 * @version 2.0.0
 * @description Defines the core data structures for the Retention & LTV Analytics Engine.
 */

import { CohortInterval, ChurnRiskLevel, UserLifecycleStatus, EngagementMetric } from './constants';

/**
 * Represents a snapshot of a user's engagement score.
 */
export interface EngagementScoreSnapshot {
  snapshotId: string;
  userId: string;
  calculatedAt: string; // ISO 8601
  overallScore: number; // A score from 0 to 100
  // Breakdown of how the score was calculated for diagnostics.
  componentScores: Partial<Record<EngagementMetric, { value: number; score: number }>>;
}

/**
 * Represents the analysis of a specific user cohort's retention over time.
 */
export interface CohortRetentionAnalysis {
  analysisId: string;
  cohortId: string; // e.g., '2025-MONTH-07'
  interval: CohortInterval;
  initialUserCount: number;
  /**
   * A map where the key is the period number (e.g., 1, 2, 3 for week 1, 2, 3)
   * and the value is the percentage of users from the cohort who were still active.
   */
  retentionCurve: Record<number, number>; // e.g., { 0: 100, 1: 65.5, 2: 50.2 }
}

/**
 * Represents the calculated Lifetime Value (LTV) for a user.
 */
export interface LifetimeValue {
  ltvId: string;
  userId: string;
  calculatedAt: string; // ISO 8601
  /** The total net revenue generated by this user for the platform. */
  totalValue: number;
  currency: string;
  /** The predicted future value this user might generate. */
  predictedFutureValue: number;
  /** The user segment this LTV calculation belongs to (e.g., 'PowerUser', 'Casual'). */
  userSegment: string;
}

/**
 * A comprehensive profile of a user from a retention perspective.
 */
export interface UserRetentionProfile {
  userId: string;
  lastUpdatedAt: string; // ISO 8601
  lifecycleStatus: UserLifecycleStatus;
  /** A prediction of the user's likelihood to churn. */
  churnPrediction: {
    riskLevel: ChurnRiskLevel;
    probability: number; // A score from 0 to 1
    keyFactors: string[]; // e.g., ['DECREASED_LOGIN_FREQUENCY', 'FAILED_QC_JOBS']
  };
  engagementScore: EngagementScoreSnapshot;
  ltv: LifetimeValue;
  /** The date the user first joined. */
  joinDate: string; // ISO 8601
  /** The date the user was last seen active. */
  lastSeenDate: string; // ISO 8601
}
