
/**
 * @fileoverview Centralized export for all Enterprise QC Pipeline Types.
 * This file provides a single, unified entry point for the entire QC type system,
 * resolving all naming conflicts through explicit aliasing. This modular approach
 * ensures maximum clarity, enterprise-grade scalability, and maintainability.
 * @version 4.0.0
 * @author DataSphere Guilds Engineering (Consolidated by Strategist-3000)
 */

// =============================================================================
// CORE ENUMS (Shared across multiple modules)
// =============================================================================
export * from './enums';

// =============================================================================
// CORE PIPELINE ORCHESTRATION & STATE
// =============================================================================
export type {
  QCPipelineOrchestrator,
  PipelineMetadata,
  SLARequirements,
  EscalationStep,
  PipelineEscalationTrigger,
  ResolverConfig,
  EvidenceRequirement,
  AutomaticAction,
  EscalationPath,
  PipelineExecutionContext,
  SecurityContext,
  ResourceAllocation as OrchestrationResourceAllocation,
  SessionData,
  PipelineConfiguration,
  LayerConfiguration,
  RetryPolicy,
  SkipCondition,
  GlobalSettings,
  NotificationSettings,
  NotificationEvent
} from './orchestration.types';

export type {
  QCPipelineState,
  QCLayerState,
  LayerCheckpoint,
  ResourceUsage,
  LayerMetadata,
  StateTransition,
  StateEvent,
  TransitionTrigger as StateTransitionTrigger,
  TransitionMetadata as StateTransitionMetadata,
  PersistenceConfig,
  ReplicationConfig,
  BackupConfig,
  ConcurrencyControl,
  StateLock,
  StateTransaction,
  StateOperation,
  Checkpoint,
  PartialState,
  StateSnapshot,
  StateValidation,
  ValidationRule,
  StateRecovery,
  RecoveryCheckpoint,
  RollbackPolicy,
  RollbackCondition
} from './state.types';

// =============================================================================
// INTELLIGENT INFRASTRUCTURE (Routing, Monitoring, Optimization)
// =============================================================================
export type {
  SubmissionType,
  QCRoutingEngine,
  RoutingStrategy,
  ConditionalLayer,
  LayerCondition,
  ConditionEvaluation,
  CostBenefitAnalysis,
  EnablementCriteria,
  TimeConstraint as RoutingTimeConstraint,
  BypassRule,
  SafetyCheck,
  AuditRequirement as RoutingAuditRequirement,
  PriorityRule,
  LoadBalancingConfig,
  HealthCheckConfig,
  FailoverConfig,
  RecoveryConfig,
  CapacityLimits,
  FallbackStrategy,
  FallbackTrigger,
  LayerSelectionAlgorithm,
  SelectionCriteria,
  SelectionWeights,
  SelectionConstraint,
  OptimizationConfig,
  ConvergenceCriteria as RoutingConvergenceCriteria,
  LearningConfig,
  ResourceAllocationStrategy,
  ResourceAllocation as RoutingResourceAllocation,
  AllocationRule,
  ScalingPolicy,
  ScalingTrigger,
  ScalingAction,
  ScalingLimits,
  ResourceMonitoring,
  MonitoringMetric,
  SamplingConfig,
  AlertConfig,
  ReportingConfig,
  ResourceOptimization,
  OptimizationConstraint as RoutingOptimizationConstraint,
  OptimizationTarget as RoutingOptimizationTarget
} from './routing.types';

export type {
  PipelineHealthStatus,
  MetricType,
  QCPipelineMonitoring,
  RealTimeMetrics,
  ThroughputMetrics,
  LatencyMetrics,
  LatencyBreakdown,
  AccuracyMetrics,
  ConfidenceDistribution,
  CostMetrics,
  CostOptimization,
  ResourceMetrics,
  ErrorRateMetrics,
  ErrorBreakdown,
  RecoveryMetrics,
  QualityMetrics,
  BusinessMetrics,
  KPIIndicators,
  AlertCondition,
  SuppressionRule,
  AlertAction,
  DashboardConfig,
  Widget,
  QueryConfig,
  TimeRange,
  VisualizationConfig,
  AxisConfig,
  LegendConfig,
  AnnotationConfig,
  Position,
  InteractivityConfig,
  DrilldownConfig,
  FilterConfig,
  LayoutConfig,
  RefreshConfig,
  AccessConfig,
  CustomizationConfig,
  PredictiveAnalytics,
  PredictiveModel,
  Forecast,
  ForecastPoint,
  ConfidenceInterval,
  AnomalyDetection,
  Anomaly,
  Recommendation,
  ImpactEstimate,
  ObservabilityConfig,
  TracingConfig,
  LoggingConfig,
  MetricsConfig,
  CollectionConfig,
  StorageConfig,
  ExportConfig,
  CorrelationConfig
} from './monitoring.types';

export type {
  QCOptimizationConfig,
  OptimizationStrategy,
  OptimizationTarget,
  OptimizationConstraint,
  PerformanceProfile,
  ProfileScenario,
  ScenarioCharacteristics,
  ProfileParameters,
  PerformanceBaseline,
  BaselineMetrics,
  PerformanceThresholds,
  ThresholdSet,
  AutoTuningConfig,
  TuningObjective,
  TuningConstraint,
  ConvergenceCriteria as TuningConvergenceCriteria,
  TuningSchedule,
  TuningTrigger,
  MaintenanceWindow,
  RollbackPolicy as TuningRollbackPolicy,
  RollbackCondition as TuningRollbackCondition,
  CachingStrategy,
  CacheLayerConfig,
  InvalidationStrategy,
  InvalidationTrigger,
  ParallelizationConfig,
  LoadBalancingConfig as ParallelizationLoadBalancingConfig,
  ResourceSharingConfig,
  ResourceLimits,
  ResourceAllocationStrategy as OptimizationResourceAllocationStrategy,
  ResourceAllocation as OptimizationResourceAllocation,
  AllocationRule as OptimizationAllocationRule,
  ScalingConfig,
  ScalingTrigger as OptimizationScalingTrigger,
  OptimizationResourceMonitoring,
  MonitoringAlert,
  AdaptiveThreshold,
  ThresholdHistory,
  AdaptationConfig,
  PerformanceTuning,
  ConnectionPoolConfig,
  MemoryConfig,
  MLOptimizationConfig,
  MLModel,
  FeatureConfig,
  PreprocessingStep,
  ModelPerformance,
  TrainingConfig,
  TrainingSchedule,
  TrainingTrigger,
  ResourceRequirement as MLResourceRequirement,
  ValidationConfig,
  HyperparameterConfig,
  HyperparameterSpace,
  InferenceConfig,
  ServingConfig,
  InferenceCaching,
  BatchingConfig,
  InferenceMonitoring,
  DriftDetection,
  FeedbackLoop,
  FeedbackSource,
  FeedbackProcessing,
  FeedbackIntegration
} from './optimization.types';

// =============================================================================
// TRANSITIONS, RESULTS, & APPEALS
// =============================================================================
export type {
  LayerTransition,
  TransitionEvent,
  TransitionCriteria,
  ConfidenceRequirement,
  BusinessRule,
  QualityGate,
  QualityThreshold,
  BypassCondition,
  TimeConstraint as TransitionTimeConstraint,
  ResourceRequirement as TransitionResourceRequirement,
  LayerDataCarryover,
  PreservedData,
  ContextualHint,
  StatePreservation,
  SharedMetric,
  CarryoverPolicy,
  TransitionValidation,
  ValidationFunction,
  TransitionMetadata,
  TransitionTrigger,
  TriggerCondition,
  TriggerAction,
  ActionRetryPolicy,
  TransitionSkipCondition,
  EscalationCondition,
  TransitionEscalationTrigger
} from './transitions.types';

export type {
  QCDecision,
  UnifiedQCResult,
  ConfidenceMetrics,
  ConfidenceCalculation,
  ConfidenceFactor,
  QCLayerResultsMap,
  QCLayerResult,
  CostMetrics as ResultCostMetrics,
  QualityFlag,
  Recommendation as ResultRecommendation,
  AggregationStrategy,
  QCProcessTimeline,
  BottleneckAnalysis,
  EvidenceChain,
  Evidence,
  IntegrityCheck,
  TraceabilityRecord,
  DecisionRationale,
  DecisionFactor,
  ReasoningChain,
  ReasoningStep,
  AlternativeDecision,
  AppealEligibility,
  AppealRequirement,
  AppealProcess,
  ReviewerType,
  RiskAssessment,
  RiskFactor,
  RiskMitigation
} from './results.types';

export type {
  QCAppealRequest,
  AppealStatus,
  AppealEvidence,
  ValidationStatus,
  EvidenceMetadata,
  AppealEvidenceChain,
  DigitalSignature,
  ReviewRequest,
  ExpertiseRequirement,
  AppealDecision,
  ImpactAnalysis,
  OperationalImpact,
  RemediationStep,
  PrecedentValue,
  AppealHistory,
  ActorInfo,
  AppealAction,
  AppealStakeholder,
  StakeholderRole,
  InvolvementLevel,
  StakeholderPermission,
  NotificationPreference,
  AppealNotificationEvent,
  DelegationConfig,
  DelegationRule,
  AppealTimeline,
  TimelineMilestone,
  TimelineExtension,
  AuditTrail,
  AuditEntry,
  AuditableAction,
  AuthorizationInfo,
  SessionInfo,
  GeolocationInfo,
  AuditContext,
  AuditOutcome,
  AuditEvidence,
  IntegrityVerification,
  RetentionPolicy,
  ArchivingPolicy,
  DeletionPolicy,
  LegalHoldPolicy,
  ComplianceAlignment,
  ComplianceFramework,
  FrameworkRequirement,
  ComplianceViolation,
  RemediationPlan,
  MonitoringRequirement,
  VerificationStep,
  ComplianceCertification,
  ComplianceAssessment,
  AssessmentFinding,
  ComplianceRecord,
  ApplicableFramework,
  LegalObligation,
  ComplianceRisk,
  RiskMitigation as ComplianceRiskMitigation,
  ComplianceControl,
  ControlTesting,
  TestResult,
  ComplianceReporting
} from './appeals.types';

// =============================================================================
// LAYER-SPECIFIC IMPLEMENTATIONS
// =============================================================================
export type {
  OnDeviceCheckType,
  DeviceValidationResult,
  OnDeviceValidationConfig
} from './on-device.types';

export type {
  AiValidatorConfig,
  AiValidationResult
} from './ai-validation.types';

export type {
  PeerReviewDecision,
  PeerReview,
  ConsensusAlgorithm
} from './peer-review.types';

export type {
  GoldStandardTask,
  GoldStandardResult
} from './gold-standard.types';

export type {
  HoneypotStrategy,
  HoneypotTask,
  HoneypotResult
} from './honeypot.types';
